apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: spring-k8-app
          image: shubhamyd07/nagp-assignment-k8:spring-k8-app-tag
          ports:
            - containerPort: 8080
          env:
             - name: DB_HOST
               valueFrom:
                configMapKeyRef:
                  name: db-config
                  key:  host
             - name: DB_NAME 
               valueFrom:
                configMapKeyRef:
                  name: db-config
                  key:  host

             - name: DB_USERNAME
               valueFrom :
                secretKeyRef :
                  name : db-secrets
                  key :  username

             - name: DB_PASSWORD
               valueFrom :
                secretKeyRef :
                  name : db-secrets
                  key :  password

---

apiVersion: v1
kind: Service 
metadata:
  name: springboot-api-svc
spec:
  selector:
    app: springboot-k8s-mysql
  type: LoadBalancer 
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
