apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-stateful
  labels:
    app: database  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
