apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: mysql:5.7
          name: database
          args:
            - "--ignore-db-dir=lost+found" 
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-secrets
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: database-pvc-stateful
---
#'Service' To Expose mysql
apiVersion: v1
kind: Service
metadata:
  name: mysql 
  labels:
    app: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: database
  clusterIP: None
